FROM python:3.7
WORKDIR /app
COPY requirements.txt .
RUN apt-get -y update &&\
    apt-get -y upgrade &&\
    apt-get install -y --force-yes git &&\
    apt-get clean

RUN apt-get -y install libspatialindex-dev
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV PYTHONUNBUFFERED=1
CMD ["sh", "run_worker.sh"]
